#
# Makefile for ICT CAS loongson2h board.
#

obj-y	+= irq.o reset.o dbg_io.o ls2h-soc-irq.o platform.o ls2h-eeprom.o 
#obj-$(CONFIG_PCI) += ls2h-pci.o
obj-$(CONFIG_PCI) += pci.o

#EXTRA_AFLAGS := $(CFLAGS)
